---
name: dummy-deployment
cloud_provider:
  template:
    name: aws_cpi
    release: bosh-aws-cpi
releases:
- name: bosh-aws-cpi
  sha1: BOSH_AWS_CPI_CHECKSUM
  url: BOSH_AWS_CPI_URL
networks:
- name: dummy
  type: vip
resource_pools:
- name: dummy
  network: dummy
  stemcell:
    sha1: c8b65794ca4c45773b6fe23b3d447dde520f07b0
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=170.3
jobs:
- name: dummy
  networks:
  - name: dummy
  resource_pool: dummy
