name: "Image: awscli"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "awscli/**"
      - ".github/workflows/awscli.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: awscli
      has_acceptance_tests: true
