name: "Image: bosh-cli-v2"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "bosh-cli-v2/**"
      - ".github/workflows/bosh-cli-v2.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: bosh-cli-v2
      has_acceptance_tests: true
