name: Deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Image to build"
      dockerfile:
        default: Dockerfile
        type: string
        description: "Dockerfile name"
      tag_suffix:
        type: string
        description: "Optional suffix for all tags"
      has_acceptance_tests:
        default: false
        type: boolean
        description: "Specify if acceptance tests are needed for this image"
      push:
        default: true
        type: boolean
        description: "Disable pushing to ghcr"

env:
  TEST_TAG: paas-tool:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.image }}
          tags: |
            type=sha,format=long,prefix=,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=branch,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=pr,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ inputs.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ inputs.image }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${{ inputs.image }}/README.md
            org.opencontainers.image.title=GOV.UK PaaS ${{ inputs.image }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build for acceptance test
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./${{ inputs.image }}
          file: ./${{ inputs.image }}/${{inputs.dockerfile}}
          load: true
          tags: ${{ env.TEST_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: ${{ inputs.has_acceptance_tests }}

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: ${{ inputs.has_acceptance_tests }}
      - name: Acceptance Tests
        env:
          DOCKER_IMAGE: "${{ env.TEST_TAG }}"
        run: bundle exec rspec ./${{ inputs.image }}/${{ inputs.image }}_spec.rb
        if: ${{ inputs.has_acceptance_tests }}

      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./${{ inputs.image }}
          platforms: linux/amd64
          file: ./${{ inputs.image }}/${{inputs.dockerfile}}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
