---
name: Deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: "Image to build"
      dockerfile:
        default: Dockerfile
        type: string
        description: "Dockerfile name"
      tag_suffix:
        type: string
        description: "Optional suffix for all tags"
      push:
        default: true
        type: boolean
        description: "Push to registries"
      platforms:
        default: linux/amd64
        type: string
        description: "Platforms to build for"
      test_platform:
        default: linux/amd64
        type: string
        description: "Platform to use for acceptance tests"

    secrets:
      CI_USER_USERNAME:
        required: true
        description: Username for logging into ghcr.io
      CI_USER_CONTAINER_REGISTRY_TOKEN:
        required: true
        description: Token for logging into ghcr.io
      DOCKERHUB_USERNAME:
        required: true
        description: Username for logging into dockerhub
      DOCKERHUB_PASSWORD:
        required: true
        description: Password for logging into dockerhub

env:
  TEST_TAG: paas-tool:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          submodules: true
      - name: Log in to ghcr.io Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_USER_USERNAME }}
          password: ${{ secrets.CI_USER_CONTAINER_REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels) for ghcr
        id: meta-ghcr
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
        with:
          images: ghcr.io/alphagov/paas/${{ inputs.image }}
          tags: |
            type=sha,format=long,prefix=,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=branch,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=pr,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ inputs.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ inputs.image }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${{ inputs.image }}/README.md
            org.opencontainers.image.title=GOV.UK PaaS ${{ inputs.image }}
      - name: Extract metadata (tags, labels) for docker hub
        id: meta-dockerhub
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
        with:
          images: governmentpaas/${{ inputs.image }}
          tags: |
            type=sha,format=long,prefix=,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=branch,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=pr,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ inputs.image }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/${{ inputs.image }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${{ inputs.image }}/README.md
            org.opencontainers.image.title=GOV.UK PaaS ${{ inputs.image }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7
        with:
          platforms: ${{ inputs.platforms }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Check if there are acceptance tests
        id: check_for_tests
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b
        with:
          files: "./${{ inputs.image }}/${{ inputs.image }}_spec.rb"

      - name: Build for acceptance test
        if: steps.check_for_tests.outputs.files_exists == 'true'
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: ./${{ inputs.image }}
          file: ./${{ inputs.image }}/${{inputs.dockerfile}}
          load: true
          tags: ${{ env.TEST_TAG }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ inputs.test_platform }}

      - name: Set up ruby
        uses: ruby/setup-ruby@5cfe23c062c0aac352e765b1b7cc12ea5255ccc4
        with:
          bundler-cache: true
        if: steps.check_for_tests.outputs.files_exists == 'true'
      - name: Acceptance Tests
        env:
          DOCKER_IMAGE: "${{ env.TEST_TAG }}"
        run: bundle exec rspec ./${{ inputs.image }}/${{ inputs.image }}_spec.rb
        if: steps.check_for_tests.outputs.files_exists == 'true'

      - name: Build and push to ghcr
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: ./${{ inputs.image }}
          platforms: ${{ inputs.platforms }}
          file: ./${{ inputs.image }}/${{inputs.dockerfile}}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta-ghcr.outputs.tags }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log in to docker hub Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: ./${{ inputs.image }}
          platforms: ${{ inputs.platforms }}
          file: ./${{ inputs.image }}/${{inputs.dockerfile}}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta-dockerhub.outputs.tags }}
          labels: ${{ steps.meta-dockerhub.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
