name: "Image: certstrap"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "certstrap/**"
      - ".github/workflows/certstrap.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: certstrap
      has_acceptance_tests: true
