name: "Image: curl-ssl"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "curl-ssl/**"
      - ".github/workflows/curl-ssl.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: curl-ssl
      has_acceptance_tests: true
