---
name: "Image: json-minify"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "json-minify/**"
      - ".github/workflows/json-minify.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "json-minify/**"
      - ".github/workflows/json-minify.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: json-minify
      platforms: linux/amd64,linux/arm64
    secrets: inherit
