---
name: "Image: node-chromium"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "node-chromium/**"
      - ".github/workflows/node-chromium.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "node-chromium/**"
      - ".github/workflows/node-chromium.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: node-chromium
      platforms: linux/amd64,linux/arm64
    secrets: inherit
