---
name: "Image: concourse-tools"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: concourse-tools
    secrets: inherit
