---
name: "Image: spruce"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "spruce/**"
      - ".github/workflows/spruce.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "spruce/**"
      - ".github/workflows/spruce.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: spruce
    secrets: inherit
