---
name: "Image: paas-prometheus-exporter"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "paas-prometheus-exporter/**"
      - ".github/workflows/paas-prometheus-exporter.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "paas-prometheus-exporter/**"
      - ".github/workflows/paas-prometheus-exporter.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: paas-prometheus-exporter
      platforms: linux/amd64,linux/arm64
    secrets: inherit
