---
name: "Image: cf-uaac"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cf-uaac/**"
      - ".github/workflows/cf-uaac.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "cf-uaac/**"
      - ".github/workflows/cf-uaac.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: cf-uaac
    secrets: inherit
