---
name: "Image: curl-ssl"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "curl-ssl/**"
      - ".github/workflows/curl-ssl.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "curl-ssl/**"
      - ".github/workflows/curl-ssl.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: curl-ssl
    secrets: inherit
