---
name: "Image: self-update-pipelines"
permissions:
  actions: write # so 'cancel-workflow-action' can function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "self-update-pipelines/**"
      - ".github/workflows/self-update-pipelines.yml"
      - ".github/workflows/build-image-base.yml"
  pull_request:
    branches:
      - main
    paths:
      - "self-update-pipelines/**"
      - ".github/workflows/self-update-pipelines.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: self-update-pipelines
    secrets: inherit
