name: "Image: json-minify"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "json-minify/**"
      - ".github/workflows/json-minify.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: json-minify
      has_acceptance_tests: true
