name: "Image: middleman"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "middleman/**"
      - ".github/workflows/middleman.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: middleman
      has_acceptance_tests: true
