name: "Image: node"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "node/**"
      - ".github/workflows/node.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: node
