name: "Image: paas-prometheus-exporter"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "paas-prometheus-exporter/**"
      - ".github/workflows/paas-prometheus-exporter.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: paas-prometheus-exporter
      has_acceptance_tests: true
