name: "Image: ruby"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ruby/**"
      - ".github/workflows/ruby.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: ruby
