name: "Image: spruce"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "spruce/**"
      - ".github/workflows/spruce.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: spruce
      has_acceptance_tests: true
