name: "Image: terraform"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
      - ".github/workflows/build-image-base.yml"

jobs:
  workflows:
    uses: ./.github/workflows/build-image-base.yml
    with:
      image: terraform
      has_acceptance_tests: true
